version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    ports:
      - "8000:80"
    entrypoint: ["/entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: